darakbooks-project/darakbooks-FE

.eslintrc.json, src/components/common/BookImage.tsx, src/components/common/FeedImage.tsx
- close #11 
- 첫번째 사진은 피드를 제외한 곳에서 사용되는 이미지로 props를 값을 통해 데이터 바인딩을 하려 했는데 실패해서 width: 90px, height: 120px;를 설정함으로써 임시로 비율을 맞춰 두었습니다.
- 두번째 부터 네번째 사진은 피드에서 사용되는 이미지로 하나의 row에 배치할 수 있는 이미지의 개수가 다를 수도 있다고 생각해서 3종 류의 width 값(33%, 50%, 100%)을 통해 가로,세로 비율 1대1로 설정해두었습니다.
=> feat: 피드 이미지, 그 외 이미지 공통 컴포넌트 구현

custom.d.ts, src/components/common/Avartar.tsx, src/components/common/Toggle/index.tsx, src/components/common/Toggle/useToggle.ts, tsconfig.json
- close #30 
- 마크업 작업시에 tailwind CSS를 통해 after, checked, + 선택자를 처리하는게 쉽지 않아서 style jsx 개념을 도입해서 css 작업을 진행하였습니다.
- toggle 버튼 클릭 시 호출 되는 함수에 전달되는 인자(boolean 데이터)를 공통 컴포넌트 또는 Hook에서 설정을 하려고 했습니다만 개인적으로 각자 문제가 있어 공통 컴포넌트를 호출 하는 곳에서 처리하도록 구현 했습니다.
- 공통 컴포넌트에서는 useEffect를 통해 처리할 수 있지만 처음 component가 mount될 때 호출되지 않아도 되는 함수가 호출되는 문제와 공통 컴포넌트 특정 페이지의 state 까지 관리해야할까?라는 의문이 생겨 일단 배제했습니다.
- Hook에서는 setState 시에 수정하면 되지만 위와 같이 역할과 관련해 의문이 생겨 배제했습니다.
- style jsx를 사용하니 로컬에서는 type check에 문제가 없었지만 배포 환경에서는 문제가 발생해 custom.d.ts 파일을 전역에 추가해 해당 에러를 해결하였습니다. 앞으로 local이나 배포 환경에서 type 관련 문제가 발생한다면 tsconfig.json에서 custom.d.ts파일을 import 하기 때문에 type 관련 문제를 처리할 수 있을 것 같습니다,
=> feat: toggle 공통 컴포넌트 구현

package.json, src/api/book.ts, src/components/book/search/SearchResultList.tsx, src/components/common/ListItem/SearchResultListItem.tsx, src/components/common/SearchInput.tsx, src/pages/book/search/index.tsx, src/types/book.d.ts, yarn.lock
- close #71 
- 마크업
- API URL 환경변수로 등록
- API 통해 데이터 fetch
- 화면에 render
- type 설정
- 남은 기능까지 구현하였을 경우 commit 개수가 많아질 것 같아 2개로 나눠 PR 올리겠습니다~
- 일단은 검색 시에 5개의 item이 render 되도록 구현하였습니다.
- authors 데이터 같은 경우 배열로 넘어와서 1개에서 많게는 여러개가 있을 것이라 예상이 되어 최대 2명의 이름만 render 하도록 처리하였습니다~
=> feat: 도서 검색 페이지 제작1

next.config.js, src/components/common/ImageComponent.tsx, src/components/common/Tab/TabItem.tsx, src/components/common/Tab/index.tsx, src/components/recruit/RecruitTab.tsx, src/layout/Layout.tsx, src/layout/RecruitLayout.tsx, src/pages/_app.tsx, src/pages/_document.tsx, src/pages/recruit/chatting.tsx, src/pages/recruit/detail.tsx, src/types/layout.ts
- close #72 
- 더미데이터를 활용하여 독서 모임 상세 페이지  구현
-> 유저의 권한에 따라 보여지는 게 달라져요.
- 참여하지 않는 경우: 가입 버튼 O  공지사항 X
- 참여하는 경우: 탈퇴 버튼 O 공지사항 O
- 모임장인 경우: 가입/탈퇴 버튼 X, 공지사항 O, 공지사항 입력창O
- 탭 관련해서 클릭 이벤트를 사용하는 곳에서 걸려고 하니까 조금 애매해져서 공통 컴포넌트 내에서 처리하도록 수정하였어요 담당자분 확인 부탁드립니다!
-> 현재 탭의 경우 오른쪽 탭에서 새로고침을 하면 페이지는 유지되지만 탭이 왼쪽 탭으로 활성화되는 버그가 있어요! 참고 부탁드려요~
- 독서모임 상세페이지와 채팅페이지가 탭을 공통 레이아웃으로 갖도록 layout 관련 기능을 추가했습니다. `Layout.tsx`는 전체 공통 레이아웃 설정할 파일인데 아직 정해진 게 없어서 비워뒀어요!
-> types 폴더에 layout 파일에 interface가 아니라 type을 사용했는데 해당 부분이 공식문서에 나와있는 부분이고 interface로 구현되기 어려운 부분인 것 같아서 일단 type으로 두었어요! 
- avatar는 공통컴포넌트를 사용했는데 모임 이미지는 next/Image를 사용했습니다. 그래서 임시로 도메인 추가해두었어요!
=> feat: 독서 모임 상세페이지 레이아웃 구현

src/api/auth.ts, src/api/axios.ts, src/pages/oauth/callback/kakao.tsx, src/utils/helpers/axiosHandler.ts
- close #65 
- 작업 내역은 commit 확인하시면 될 것 같습니다.
- 비 로그인 유저 => Bottom Nav Bar로 접근 시 모달 render, url로 접근시 main으로 redirect
- 유저(토큰이 유효) => 데이터를 정상적으로 받아옴
- 유저(토큰이 만료) => 새로운 액세스 토큰을 받기 위한 요청을 함(해당 요청과 관련된 작업이 아직 백에서 완료되지 않아 새로운 토큰을 받지 못하고 있습니다)
- 영상의 메인에 Bottom Nav Bar 및 로그인 버튼은 기능 확인을 위해서 개발 환경에서 따로 추가한 것 입니다.. 해당 소스코드까지 commit 하는 것은 불 필요하다고 생각해 올리지 않았기 때문에 배포환경에서는 보이지 않을 겁니다.
- 궁금한 것 있으시면 질문해주세요~
=> feat: 기존 액세스 토큰 유효기간 만료 시 새로운 액세스 토큰 발급

src/components/common/ListItem/SearchResultListItem.tsx, src/components/recruit/RecruitInfinityScrollLists.tsx, src/pages/recruit/index.tsx
- close #91 
- 작업 내역은 commit을 통해 확인하시면 됩니다~
- TanStack Query, getServerSideProps를 통해 특정 key 값을 가지고 있는 query에 데이터 pre-fetch
- 아래 사진 같은 경우 pages의 도서 리스트 데이터가 4개인데 1개는 pre-fetch 했으므로 API 호출은 3번만 합니다.
- 데이터 4개
- API 호출은 3번만
- 현재 독서 인원 모집 리스트 데이터가 없기도하고 레이아웃을 잡기 위해 카카오 도서 검색 API 사용했습니다.
- pre-fetch를 하다보니 Hydration Error가 발생해 useEffect를 통해 컴포넌트가 mount 됬을 때 리스트를 render 해줌으로써 문제를 해결 했습니다
- Hydration Error => pre-rendering된 React 트리와 브라우저에서 첫번째 렌더링하는 동안 렌더링된 React 트리 사이의 차이가 발생하기 때문에 나는 오류
- stale time을 설정하지 않으면 pre-fetch한 캐싱 값을 사용하지 못하므로 넉넉하게 20초로 설정해두었습니다.
- 참고 자료 => https://velog.io/@dee0518/Next.js-react-hydration-error
=> feat: 독서 인원 모집 페이지 제작

src/api/recruit.ts, src/pages/recruit/detail/index.tsx
- close #151  
- `getServerSideProps`를 통해서 groupId로 query를 받아서 fetch를 합니다!
- 아직 그룹 api에서 모임장, 멤버 여부, 모임장 id, 유저 리스트가 아직 안 들어오는 상황이어서 해당 필드를 사용하는 부분은 dummy 데이터를 사용하게 두어서 dummy 데이터를 남겨두었고 백엔드에서 완성되면 다시 수정할 예정입니다!
=> feat: 독서 모임 상세 페이지 api 연결

src/api/main.ts, src/api/recruit.ts, src/components/common/Header.tsx, src/components/recruit/detail/RecruitParticipationControl.tsx, src/components/recruit/detail/RecruitStatusSelectModal.tsx, src/pages/index.tsx, src/pages/recruit/detail/index.tsx, src/recoil/modal.ts
- close #148  
- 독서모임 상세페이지에서 모임장 권한에 따라 추가하였습니다.
1. 상세페이지에서 모집여부 변경 가능
2. 모임 수정 페이지로 이동 가능
- 아직 해당 페이지가 없어서 주소는 비워뒀습니다.
- Header 컴포넌트에서 추가 스타일 적용할 수 있도록 수정하였습니다!
- 멤버 강퇴 기능은 아직 서버에서 userGroup이 제대로 들어오지 않아서 해당 부분 적용되면 구현할 예정입니다!
- 아이콘은 다 임시로 넣어둔 거예요! 시온님께서 파일 전달해주시면 그 때 다시 적용하겠습니다!
모집 여부 변경 모달 이미지
=> feat: 독서 모임 상세페이지 모임장 권한 구현

src/api/recruit.ts, src/components/recruit/RecruitForm.tsx, src/components/recruit/RecruitFormUserInput.tsx, src/components/recruit/RecruitOpenForm.tsx, src/hooks/useGroupForm.ts, src/pages/recruit/detail/index.tsx, src/pages/recruit/update.tsx, src/pages/recruit/write.tsx, src/types/recruit.d.ts
- close #169 
- commit 내역을 통해 작업 내역 확인하시면 될 것 같습니다~
- 페이지 디자인은 독서 모임 개설 페이지와 동일합니다~
- 현재 GroupFormStateObjProps, GroupList 이 두 interface를 하나의 interface로 수정하는 작업을 해야할 것 같습니다~
- @YJZero 소스코드 중복 방지를 위해  patchReadingClassChange에서 서버에 넘겨줄 데이터 처리하는 하는 것은 어떨까요?
ex) => 같은 파일의 postReadingClassOpen 함수
=> feat: 독서 모임 수정 페이지

src/components/common/BookShelfPreview.tsx, src/components/main/bestRecruit/BestRecruitListItem.tsx, src/pages/book/detail/index.tsx
- close #213  
온보딩 페이지 관련 pr 에도 적혀있는 내용 수정한 pr 입니다.
- 미로그인 유저가 메인페이지 접근 시 온보딩 페이지에서 온 게 아니라면 온보딩페이지로 이동됩니다. 그런데 Link로 isAuthorized를 체크하는 부분에서 Link의 `''` 로 이동 시 메인으로 이동되어 온보딩으로 이동되어 버리는 문제가 생깁니다.
그래서 Link 부분을 useRouter로 모두 변경하였습니다!
- 빠진 부분이나 잘못된 부분이 있다면 알려주세요!
- bottomNav에서 기록 버튼도 Link처럼 path가 설정되어 있는데 이 부분도 만약 위와 비슷한 일이 발생한다면 path를 변경하거나 query 값을 추가하여 온보딩으로 안 가도록 처리해야 할 것 같습니다!
-> 온보딩 페이지 머지되면 확인 후 수정하겠습니다.
=> refactor: isAuthorized 체크 Link -> useRouter로 변경

src/pages/recommend/result.tsx
- close #232  
- 책장에 이미 담은 책일 때 에러 처리 부분입니다.
- 재홍님께서 이미 작성해주신 부분이 있어서 동일하게 적용해두었어요!
- 지금은 alert인데 나중에 토스트 ui 등으로 적용해도 좋을 것 같아요!
=> fix: 추천 페이지 이미 담은 책일 때 에러 처리

src/components/main/bestRecruit/BestRecruitListItem.tsx
- close #256  
그룹 리더 api에서 그룹 id를 쿼리 키 값으로 넣지 않아서 캐싱 데이터를 사용하여 그룹과 그룹 리더 프로필 불일치 버그가 생기고 있었습니다! 그래서 그룹 아이디를 쿼리 키 값으로 추가했어요~
=> fix: 메인 인기 모임 쿼리 키에 group Id 추가

src/pages/book/search/index.tsx, src/pages/recruit/index.tsx
- close #268 
- 이슈에 작업 진행 이유를 작성해두었습니다~
- 해당 문제가 발생한 이유는 크기가 넘치는 태그에 position: fixed를 설정해주었기 때문이였습니다. position: fixed를 설정하게 되면 body에 설정된 max-width가 적용이 왜 안되는지는 모르겠습니다.(아시는 분 있으시면 리뷰 달아주세요!)
- 디자인 결과
=> design: 페이지 max-width 설정

src/components/recruit/RecruitInfinityScrollLists.tsx
모임 개설 시에도 최 하단에 아이템이 추가되기 때문에 반영 안되는 문제 있었음
- close #289 
- 블로그에 작성할 예정이여서 길게 기록했습니다~ 내용 참고하셔서 소스코드 보시면 이해에 도움이 되실 겁니다! 
- 이슈에 문제 상황 요약해두었습니다~
- 문제 상황
- 데이터를 정상적으로 fetch 하지 못하기 때문일 것이라는 1차적인 생각이 들었습니다.
- 네트워크 탭 
- api 함수 호출하는 곳
- 위의 사진과 같이 정상적으로 수정된 데이터를 fetch 해오는 것을 볼 수 있습니다. 반면에 컴포넌트에서 콘솔에 데이터를 찍어보면 이전데이터가 보입니다...
- 데이터 fetch 자체에 문제가 있는 것이 아니라 최하단에서만 해당 문제가 발생하니까 inView에 문제가 있지 않을까라는 생각을했습니다. 그 생각에 착안해 스크롤이 최하단일 때와 그 이외의 상황일 때 useEffect 안에서 콘솔을 찍어보았습니다.
- 최하단에서는 inView가 true이기 때문에 fetchNextPage 호출
- 최하단이 아닌 경우에는 fetchNextPage 호출 안함
- 위의 결과를 바탕으로 최하단일 때도 fetchNextPage가 호출되지 않도록 함으로써(hasNextPage 사용) 문제를 해결할 수 있었습니다.
- fetchNextPage가 호출 되면 수정 된 데이터를 render 하지 못하는 이유
- 결론부터 말씀드리면 최신 데이터를 반영하지 못하는 이유는 `fetchNextPage 호출`이지만 구체적인 이유와 `enabled에 의한 query 활성화`와의 인과관계를 정확히 파악하지는 못했습니다.
- 저는 단지 …
=> fix: 스크롤이 최 하단 상태일 때 보이는 리스트 아이템 수정 시 반영 안됨

src/components/common/Header.tsx, src/components/recruit/RecruitInfinityScrollLists.tsx, src/pages/recruit/index.tsx, src/pages/recruit/update.tsx, src/pages/recruit/write.tsx
- close #291 
- 이슈에 해당 작업을 해야하는 이유 작성해두었습니다.
- 독서 모임 개설(책 매니아들 이라는 제목의 모임 생성)
- 독서 모임 수정(독서 하는 거인 => 독서 하는 거인 수정)
- 일단 제 판단하에 해당 작업을 진행했는데 도입해도 괜찮을 것 같다고 생각하시면 코멘트 및 디자인도 부탁드려야 할 것 같습니다!
- 현재 독서 모임 개설 후 상세 페이지로 이동하지 않는 이유는 이전 작업의 PR이 Merge 되지 않아서 입니다.
=> fix: 독서 모임 개설, 수정 후 refetch 하는 동안 comment render

src/components/recruit/RecruitInfinityScrollLists.tsx
- close #286 
- 이슈에 발생했던 버그 관련해 작성해두었습니다.
- 해결 방법
- groups[index] 제거
- groups[index] => n번째 그룹데이터의 n번 index의 데이터가 존재하면 true
- 예를들어 현재 총 30개의 리스트 아이템이 있고 스크롤 할 때 마다 5개의 아이템을 render 한다고 가정하겠습니다.(총 그룹 수: 6개)
- 첫번째 그룹 => 첫번째 그룹의 groups[1(그룹번호)](데이터가 있어서 render)
- 두번째 그룹 => 두번째 그룹의 groups[2](데이터가 있어서 render)
- 다섯번째 그룹 => 다섯번째 그룹의 groups[5](1개의 그룹에는 5개의 아이템만 있기 때문에 특정 그룹 index의 최대값은 4이다. 하지만 5번째 index를 조회함으로 인해 false가 반환되고 그로인해 다섯 번째 그룹에 해당하는 리스트가 render가 안됨. 그 뒤의 그룹도 마찬가지 이유로 render가 안됬다.)
- 처음에는 index가 각 그룹 아이템에 따라 달라진다고 생각을 해서 해당 코드를 작성했습니다. 하지만 그룹에 따라 index가 달라지기 때문에 이런 문제가 발생하였습니다.
=> fix: 리스트 데이터 render 하지 못하는 문제

src/components/book/search/InfinityScrollLists.tsx, src/components/common/SearchInput.tsx, src/pages/book/search/index.tsx
- close #303 
- 도서 검색페이지에 발생하는 오류 이슈에 작성해두었습니다.
- 다른 페이지 갔다 왔을 때 input에 입력한 제목 그대로 유지되지 않는 이유 및 해결 방법
-  이유 => SearchInput 컴포넌트의 사용자가 입력하는 텍스트의 데이터를 `const [inputData, setInputData] = useState('');`로 관리하기 때문에 다른 페이지 갔다가 다시 페이지가 re-render 되면 제목 유지가 안 됨
- 해결 방법 => re-render 될 때 상위 컴포넌트로부터 전달 받은 props 값이 render 되도록 함으로써 해결
-  검색 후 다른 페이지 갔다가오면 검색 안됨
- 검색이 안되는 이유는 enables 값이 false이기 때문이라고 생각을 했다.
- `(enabled: !!searchKeyword && !bookSearchData.current)`
- 새롭게 검색 하는 상황에 콘솔에 찍어보니 bookSearchData.current 값이 존재했다.
- 그래서 새롭게 검색 할 때 이전 쿼리값을 삭제하는 방법을 시도해보았다.(queryClient.removeQueries)
- 그러나 여전히 검색이 되지 않았고 오히려 이전에 검색한 데이터가 캐싱되지 않으니 UX 저하라는 문제가 발생했다.
- 그러다 문득 useRef의 current 값은 컴포넌트가 mount 될 때 설정된 값을 re-render가 되어도 계속 유지 한다는 말이 생각났다. 그로인해 검색어가 바껴도 bookSearchData가 이전 데이터를 가지고 있으므로 쿼리가 비 활성화 되어 검색이 안되었던 …
=> fix: 도서 검색 페이지

src/components/common/BottomNav.tsx
- close #329  
- bottom nav 기록 부분에서 as를 제거하지 않아 주소가 잘못 전달되고 있어서 새로고침 시 메인으로 가는 버그가 있었습니다! as 제거로 해결하였습니다.
- bottom nav에서 `isClick` 관련 경고가 계속 출력 되어 이 부분 제거하였습니다! @Park-min-hyoung 확인 부탁드립니다!
- `isClick` 이 스타일에 전달되는 요소인데 Dom에도 그려지는 게 문제라고 합니다. 따라서 `$` 표시를 붙임으로써 DOM요소로 렌더링 되지 않도록 할 수 있다고 하네요! 
`$` 표시 관련 문서입니다.
https://styled-components.com/docs/api#transient-props
=> fix: bottom nav 기록 as 제거 및 경고 제거

src/components/common/Modal.tsx, src/components/recruit/detail/RecruitParticipationControl.tsx, src/components/recruit/detail/member/MemberListItem.tsx, src/pages/recruit/detail/index.tsx
- close #326  
width에 따라 모달이 반응형으로 동작할 수 있도록 %로 변경하였습니다!
- width 280px 일 떄
- width 390px 일 때
=> design: 모달 반응형으로 변경

src/components/main/mainRecordFeed/FeedItem.tsx, src/components/main/mainRecordFeed/RecordFeedList.tsx, src/hooks/useRememberScroll.ts, src/pages/book/record/index.tsx
- close #355  
메인페이지 기록 피드 페이지에서 특정 피드 클릭한 후 다시 리스트로 돌아왔을 때 이전 스크롤 위치 기억하도록 하였습니다.
- 다른 곳에서도 쓰일 것 같아서 훅으로 구현하였어요!
- 새로고침 시에도 스크롤 위치를 저장할 수 있도록 로컬스토리지로 구현하였습니다.
- 메인 피드 api에 staleTime을 5분으로 지정하여 기록을 보고 돌아왔을 때 api 호출을 줄일 수 있도록 하였어요! 그래서 기록 작성 후에 해당 쿼리를 초기화하는 것을 추가하였습니다.
- 만약 기록 작성 후 초기화가 필요한 쿼리가 있다면 쿼리키 `feed` 를 추가하면 될 것 같습니다!
=> feat: 메인 기록 무한스크롤 페이지 이동 시 스크롤 유지

src/components/common/BottomNav.tsx, src/components/recommend/RecommendResultModal.tsx, src/layout/ProfileLayout.tsx, src/pages/index.tsx, src/pages/login/index.tsx, src/pages/onboarding/index.tsx, src/recoil/onboarding.ts
- close #362  
- 비로그인 시 최초 접속 제외하고 온보딩으로 가지 않도록 처리하였습니다.
(로그인 페이지 둘러보기 버튼, 로그아웃 시 .... etc)
- 기존에 query로 처리하고 있었는데 로그아웃시 atom 값이 업데이트되면서 구독하고 있는 컴포넌트가 업데이트되어 바로 온보딩 페이지로 이동되면서 router 처리가 적용되지 않고 있었습니다. 따라서 로그아웃시 query값을 전달할 수 없을 것 같아 recoil 을 사용하는 방법으로 변경하였습니다~
- 리팩토링 
- 최초 접속을 제외하고 온보딩을 가지 않기 때문에 페이지 마다 recoil값을 변경하지 않고 로그아웃할 때만 변경하면 되지 않을까? 했는데 로그아웃 시에도 메인으로 가야해서 처리하기가 애매하여 일단 페이지마다 리코일값 변경하도록 하였습니다. 추후 아이디어가 떠오르면 리팩토링 예정입니다!
- 현재 온보딩으로 리다이렉션될 때 깜빡임 현상이 있는데 이는 추후 리팩토링 할 때 수정할 예정입니다~
=> feat: 온보딩 리다이렉션 재적용

src/components/recruit/RecruitFormUserInput.tsx
- close #388 
- 독서 모임 개설, 수정 페이지에서 온라인 버튼 클릭하면 지역 select box 제거되도록 구현하였습니다.
- 결과물(오프라인 버튼)
- 결과물(온라인 버튼)
=> design: 독서 모임 개설, 수정 페이지 온라인 버튼 클릭 시

src/components/book/search/InfinityScrollLists.tsx, src/pages/book/record/search.tsx
- close #383 
-도서 검색 페이지, 도서 선택 페이지 검색 탭 기록이 공유되는 현상 해결
- 도서 선택 페이지의 도서 검색 탭을 누르면 도서 제목을 초기화되게 하였습니다. 이렇게 하면 검색탭을 누를 때마다 초기화가 되어 책장 탭, 검색 탭 이동할 때마다 초기화가 되고, 검색 탭으로 이동했다가 네비게이션을 이용하여 도서 검색 페이지로 가도 데이터가 초기화가 되게 됩니다. 일단 이렇게 구현했는데 리팩토링 때 좀 더 효율적인 방법이 있나 고민해보고 적용해야할 것 같습니다.
=> fix: 도서 검색 페이지, 도서 선택 페이지 검색 탭 기록이 공유되는 현상 해결

src/components/main/mainRecordFeed/FeedItem.tsx
- close #407 
- 메인페이지 피드에서 데스크탑 모드일 시 이미지가 안보이는 현상을 해결하였습니다.
=> fix: 메인 피드 데스크탑 모드 시 이미지 안보임 해결

package.json, src/lib/gtag.ts, src/pages/_app.tsx, src/pages/_document.tsx, yarn.lock
- close #426
- 이슈에 ga 연동한 이유 작성해두었습니다.
- 사이트에 처음 접근 했을 때 ga 관련 js 파일을 응답
- 사이트에 처음 접근 했을 때 datalayer를 조회 해보면 gtm과 관련된 내용이 보임
- 온보딩 페이지에서 메인으로 이동했을 경우 gtm 기록 변경 이벤트 발생
- 사진이 생각보다 작아서 한번 클릭 한 다음 봐주세요~
- 현재 정상적으로 연동되었는지 확인하지 않았기 때문에 배포 후에 다시 확인해봐야 할 것 같습니다!
=> chore: ga 연동

src/components/recruit/detail/RecruitStatusSelectModal.tsx
- close #424 
모집여부 변경에서 로딩이 걸렸을 때 버튼을 여러 번 클릭하는 걸 막는 방법으로 버튼 클릭 시 바로 모달을 닫고 ui를 업데이트하는 낙관적 업데이트를 적용하였습니다.
- 느린 3G로 테스트한 화면입니다. (네트워크 대기중임에도 ui는 낙관적 업데이트 진행)
=> fix: 모집여부 변경 모달 낙관적 업데이트 적용

src/pages/_app.tsx
- close #429  
메인에서만 발생하는 현상인 줄 알았는데 **스크롤이 되는 모든 페이지에서는 아래 gif와 같이 뒤로가기를 누르면 스크롤이 하단으로 내려갔다가 페이지 이동되는 모습**이 보였습니다.
<br/>
해당 현상은 브라우저에서 이전 브라우저의 스크롤 위치를 자동으로 복원하려고 하는 기본 동작으로 인해 발생하는 것 같습니다! 해당 기능을 조절하였더니 아래와 같이 해당 버그 없이 잘 동작합니다!
=> fix: 뒤로가기 시 스크롤 하단으로 움직임 수정

src/hooks/useRouterLoading.ts
- close #430  
페이지 로딩 시간이 0.5초 이상 걸리는 경우에만 로딩 스피너가 보이도록 하였습니다. 시간은 임의로 설정했습니다! 조정이 필요할 것 같다면 말씀해주시면 감사하겠습니다~~
- 0.5초 이상 걸리는 페이지 이동만 로딩 스피너 보이도록 작업 결과
=> refactor: 일정 시간 이상 걸리는 로딩만 스피너 보이도록 처리

src/components/recommend/BookRecommendGuide.tsx, src/pages/recommend/complete.tsx, src/pages/recommend/userinput.tsx
- close #457  
- 책 추천 실패로 돌아가기 시 `recommend/userinput` 페이지로 이동할 수 있도록 변경
- `독서메이트 00 입니다` -> `독서메이트입니다` 로 변경 
- complete 페이지에 헤더 추가
- 로그인 시 담기와 상세보기가 가능한데 상세보기를 한 경우나 아무것도 하지 않은 경우다른 페이지로 이동할 수 있는 방법이 없어 뒤로가기 버튼을 추가하였습니다.
- 상세보기를 한 경우에도 bottom nav 가 없고 상세 페이지에서 뒤로가기 하면 complete 페이지로 돌아와서 다른 페이지로 이동이 불편하더라구요!
- 간혹 api에서 response 데이터가 온전한 객체로 넘어오지 않을 때가 있습니다. 그 때 bookTitle이 undefined가 되는데 이때 임시로 찾을 수 없다는 에러 메세지가 뜨도록 해두었습니다! 온전한 객체가 넘어오게 되면 제거할 예정입니다~
=> refactor: 추천페이지 수정

src/pages/book/search/index.tsx
- close #465 
- 이슈에 작업의 필요성을 작성해 두었습니다~
- 성능 개선 전 프로덕트 환경에서 라이트 하우스를 통해 성능 측정(`성능 점수: 89점, LCP: 2.1s`) 
- Light House는 프로덕트 환경에서 측정 하는 것이 정확하다고 합니다~(프로덕트 환경 yarn build =>  yarn start)
- Dynamic import를 사용해 무한 스크롤 리스트, Bottom Nav Bar 컴포넌트 동적으로 import(`성능 점수: 95점, LCP: 1.5s`)
- prettynigh font를 사용하는 곳에서만 설정할 경우(`성능 점수: 99점, LCP: 0.9s`) 
- next/font/google 같은 경우는 성능 저하에 문제가 되지 않았지만 next/font/local 같은 경우 `컴퓨터에 설치된 로컬 폰트 파일을 사용하므로, 크기가 크고 다운로드 시간이 더 걸릴 수 있다.` 이와 같은 이유로 인해 성능 저하에 문제가 되는 것 같습니다~
- 결론 : 최적화 작업을 통해 성능 점수를 89점에서 99점으로 올렸으며 FCP, LCP 소요시간을 각각 37.5%, 57% 개선하였습니다!
=> refactor: 도서 검색 페이지 성능 개선

src/pages/book/search/index.tsx
- close #490 
- 문제 상황
- 성능 최적화를 위해 설정한 Dynamic import(Bottom Nav Bar)를 제거하니 정상적으로 렌더링 됩니다~
- Dynamic import로 인해 해당 error가 왜 발생했는데 모르겠습니다. 아시는 분 있으면 공유부탁드립니다~
=> fix: 도서 검색 페이지 새로고침 시 렌더링 안되는 문제

src/components/common/BottomNav.tsx, src/components/common/Modal/Confirm.tsx
- close #494 
- slow 3g 속도에서 메인 페이지 접근시 Bottom Nav Bar의 아이콘이 모두 render 되는데 7s가 걸리고 priority props를 설정하면 4s에 render 됩니다. 
- desktop에서 render 되는 Login Modal이 컨텐츠 영역을 벗어나는게 UI적으로 좋지 못해 수정하였습니다~
=> Design/#494 update UI
