darakbooks-project/darakbooks-FE

- .github/workflows/pullRequest.yml
- package.json
- close #5 
- git action을 통해 Continuous Integration(CI) 워크플로우 구축
- PR이 open 및 update 시 TypeScript 및 ESLint를 통해 코드 품질 검사
- 코드 품질 검사를 통해 코드 안정성 확보를 위해 도입
- 빌트 테스트 및 배포는 vercel 측에서 수행하므로 생략
> chore: git action을 통해 PR open 및 update 시 type, lint 오류 check

- src/pages/_app.tsx
- close #19 
- _app.tsx파일에 react-query를 hydration 방법으로 적용하였습니다.
https://velog.io/@arthur/React-Query-with-Next.js-%EC%84%9C%EB%B2%84-%EC%82%AC%EC%9D%B4%EB%93%9C-%EB%A0%8C%EB%8D%94%EB%A7%81
> chore: react-query hydration 설정변경

- src/components/common/Avartar.tsx
- close #31 
- 이슈에 오류 발생이유 적어두었습니다.
> fix: 빌드 오류 해결

- src/api/auth.ts
- src/components/common/BottomNav.tsx
- src/hooks/useAuth.ts
- src/pages/oauth/callback/kakao.tsx
- src/recoil/atom/auth.ts
- close #52 
- 이슈에 작업 이유 작성해두었습니다.
- 현재 서버로부터 응답을 받을 수 없어 로그인 여부를 서버에서 check 할 수 없으므로 새로고침하면 자동으로 로그아웃 됩니다.
- 기존에는 token을 상태로 관리했지만 보안에 문제점을 느껴 로그인 여부를 상태로 관리하도록 변경 했습니다. 다만 API 호출 하는 부분에서 token을 조회할 수 있으므로 이 부분을 백엔드분과 조율하거나 보안적으로 괜찮은지 check 해봐야 할 것 같습니다.
> fix: 새로고침 시 로그아웃되는 문제 해결

- src/components/auth/LoginModal.tsx
- src/components/common/BottomNav.tsx
- src/pages/_app.tsx
- close #49 
- 비 로그인 유저가 유저 전용페이지로 이동하려는 경우 모달 창을 render 함으로써 사용자가 로그인 여부를 결정할 수 있도록 구현
> feat: 로그인 여부 모달 제작

- package.json
- src/components/auth/LoginButton.tsx
- yarn.lock
- close #66 
- 라이브러리 도입 이유 이슈에 작성해 두었습니다~
- 자동 정렬이랑 자동 완성이 안되는 불편한 점이 있는 것 같아요. 익스텐션 등을 찾아서 보완해야 할 것 같습니다!
> chore: tailwind-styled-component 설치

- src/components/book/record/RecordForm.tsx
- src/components/common/Modal.tsx
- src/pages/profile/index.tsx
- src/recoil/modal.ts
- close #60 
- 프로필 변경 로직 구현? 구상 하였습니다.
- 내 책장, 전체 피드, 마이 독서 모임 탭 구현하였습니다.
- api가 있는 것 처럼 상상하면서 코드를 작성하니 api 연결했을 때 제대로 돌아갈지 모르겠네요
- 공개 여부 설정하는 것은 테스트 회원을 만들고 구현해야할 것 같습니다
> feat: 프로필 정보 수정, 글 목록 레이아웃

- package.json
- src/api/book.ts
- src/components/book/search/InfinityScrollLists.tsx
- src/components/book/search/SearchResultList.tsx
- src/components/common/ListItem/SearchResultListItem.tsx
- src/pages/_app.tsx
- src/pages/book/search/index.tsx
- yarn.lock
- close #73 
- 작업은 이슈 및 commit 내역 제목을 통해 작성해두었으니 참고하시면 될 것 같습니다.
- commit 제목이 간결한 것은 commit description에 구체적을 작성해두었으니 클릭하셔서 확인하시면 될 것 같아요.
- 무한 스크롤 관련해 기본 기능은 구현했는데 개선할 부분이나 사이드 이펙트가 많아서 추가 작업이 필요할 것 같습니다.
> feat: 도서 검색 페이지 제작 2

- package.json
- yarn.lock
- close #105 
- install next/font
> chore: install @next/font

- src/hooks/useImage.ts
- close #117 
- 파일 등록 api return 변수명 수정
> fix: 파일 등록 api return 변수명 변경

- src/pages/book/feed/index.tsx
> design: 변경된 디자인 적용

- src/components/book/record/SelectModal.tsx
- src/layout/BookSelectLayout.tsx
- src/pages/book/record/search.tsx
- src/pages/book/record/select.tsx
- src/recoil/modal.ts
- tailwind.config.js
- close #129 
- 도서 선택 페이지 공통 레이아웃 제작
- 도서 선택 페이지 내 책장 디자인
> design: 도서 선택 페이지 디자인

- src/pages/book/record/index.tsx
- close #136
- react-query에 enabled 설정
> fix: enabled 설정

- src/pages/profile/edit.tsx
- src/pages/profile/myfeed.tsx
- src/pages/profile/myrecruit.tsx
> feat: 마이 페이지 라우트 구성

- src/layout/ProfileLayout.tsx
- src/pages/book/record/select.tsx
- src/pages/profile/index.tsx
- src/pages/profile/myfeed.tsx
- src/pages/profile/myrecruit.tsx
- close #135 
- 마이페이지 공통 레이아웃
- 내 책장, 내 기록 디자인
> design: 마이 페이지 디자인

- src/components/common/Header.tsx
- src/components/recruit/detail/member/MemberListItem.tsx
- src/layout/Layout.tsx
- src/pages/recruit/detail/member.tsx
- src/styles/globals.css
- close #147 
독서 모임 멤버 페이지 디자인 구현하였습니다.
`recruit/detail/member` 주소로 확인 가능합니다!
사용자 눌렀을 때 마이페이지로 이동하는데 이 때 userId는 어떤 식으로 넘기게 될 지 몰라서 임의로 추가해두었어요~
> feat: 독서 모임 멤버 페이지 구현

- src/api/bookshelf.ts
- src/api/record.ts
- src/pages/book/detail/index.tsx
- src/types/bookshelf.d.ts
- close #152 
- 책장에 담기 구현
- 무한스크롤은 구현하지 못하였습니다.
> api: book-detail

- src/components/common/ListItem/ReadingGroupRecruitment .tsx
- src/pages/recruit/index.tsx
- close #154 
- preview의 `/recruit`를 통해 작업 내역을 확인하실 수 있습니다~ 
- 현재 groups API의 모임에 참여중인 유저의 데이터가 응답되지 않는 관계로 일단은 Avatar Button은 마크업하지 않았습니다.
- 시간이 될 때 font 설정도 필요해 보입니다~
> desgin: 독서 모임 리스트 페이지

- src/api/book.ts
- src/api/record.ts
- src/pages/book/detail/index.tsx
- close #161 
- 도서 상세 페이지 무한스크롤
- 스크롤 위치 저장하는 부분은 구현이 안되었습니다.
> feat: 도서 상세 페이지 무한스크롤

- next.config.js
- src/api/record.ts
- src/pages/book/detail/index.tsx
- src/pages/book/feed/index.tsx
- close #163 
- 도서 상세에서 넘어오는 독서 기록 페이지네이션 구현
- 너무 힘들었어요..
> api: 피드 페이지네이션 구현

- src/pages/profile/myrecruit.tsx
> design: 나의 모임

- src/components/common/BottomNav.tsx
- close #168 
- 이슈에 작업 내역 작성해두었습니다.
- 로그인 버튼 눌렀을 때 모달이 render 안 되고 바로 login 페이지로 이동하도록 구현하였습니다. 사용자가 로그인 버튼을 누른 경우는 로그인을 원해서 눌렀다고 생각하기 때문에 다시 되 묻는 것은 불 필요하다는 생각이 들어 제거했습니다~
> refactor: bottom nav bar

- src/api/record.ts
- src/pages/book/detail/index.tsx
- src/pages/book/feed/index.tsx
- close #177 
- get records 타입 수정, 적용
- 피드 페이지 네비게이션 적용
- 페이지네이션 첫 페이지, 마지막 페이지 판별 미구현
> feat: get records 타입 수정, 적용

- src/api/bookshelf.ts
- src/pages/profile/index.tsx
> api: 내 책장 불러오기

- src/api/main.ts
- src/api/recruit.ts
- src/components/common/Avartar.tsx
- src/components/common/ImageComponent.tsx
- src/components/common/Modal.tsx
- src/components/main/bestRecruit/BestRecruitListItem.tsx
- src/components/recruit/detail/RecruitParticipationControl.tsx
- src/pages/recruit/detail/index.tsx
- src/recoil/modal.ts
- src/types/recruit.d.ts
- tailwind.config.js
- close #175  
- 모달 가운데 정렬되도록 수정했어요! 참고 부탁드립니다.
- 추후에 배경 스크롤 안되도록 수정되면 좋을 것 같아요!
- 가입/탈퇴 api 연결 하였습니다.
- 서버 response 데이터 변경사항 적용하였습니다.
❗ 현재 가입 api가 성공은 하는데 해당 가입한 유저 데이터가 들어오지 않아서 탈퇴 관련해서는 테스트를 못해봤습니다! 추후에 api 수정되면 테스트할 예정입니다.
❗ 브랜치에서 작업하면서 이미 커밋한 상태라 rebase를 못했어요! 그래서 변경사항들이 있어서 충돌이 나는데 어디서 나는지 보고 충돌 해결하겠습니다~
> feat: 그룹 가입/탈퇴 api 연결

- src/pages/index.tsx
- close #185  
메인 페이지 hydration error 가 안나다가 갑자기 발생해서 해결하였습니다!
[관련 스택오버플로우 글](https://stackoverflow.com/questions/72673362/error-text-content-does-not-match-server-rendered-html)
> fix: 메인 페이지 hydration error 해결

- src/api/auth.ts
- src/components/book/record/SelectModal.tsx
- src/components/common/ListItem/SearchResultListItem.tsx
- src/pages/book/record/search.tsx
- src/pages/book/record/select.tsx
- src/recoil/modal.ts
- src/types/modal.d.ts
- close #192 
- 도서 선택 페이지 책장 구현
- 도서 선택 페이지 검색 구현
> feat: 도서 선택 페이지 구현

- src/components/book/record/SelectModal.tsx
- src/components/common/ListItem/ReadingGroupRecruitment .tsx
- src/components/main/bestRecruit/BestRecruitListItem.tsx
- src/components/recruit/RecruitOpenForm.tsx
- src/components/recruit/detail/RecruitParticipationControl.tsx
- src/components/recruit/detail/RecruitStatusSelectModal.tsx
- src/layout/BookSelectLayout.tsx
- src/layout/ProfileLayout.tsx
- src/pages/book/detail/index.tsx
- src/pages/book/record/index.tsx
- src/pages/book/record/select.tsx
- src/pages/index.tsx
- src/pages/profile/edit.tsx
- src/pages/profile/index.tsx
- src/pages/profile/myrecruit.tsx
- src/pages/recruit/detail/index.tsx
- src/pages/recruit/detail/member.tsx
- src/pages/recruit/write.tsx
- tailwind.config.js
- close #200 
메인컬러를 변수로 지정해놨습니다! `main` 으로 지정해두었습니다
기존의 메인컬러 일괄 변경하였습니다! 놓친 부분도 있을 것 같고 해당 되는 부분 아닌데 변경된 경우 말씀해주시면 반영해두겠습니다~
> design: 메인 컬러 변수 설정 및 일괄 변경

- src/components/common/ListItem/SearchResultListItem.tsx
- close #206 
- 라우트 경로 수정하였습니다.
> fix: 라우트 경로 수정

- src/components/common/ListItem/SearchResultListItem.tsx
- close #194 
- 이슈에 해당 작업을 진행한 이유를 설명해뒀습니다~
> refactor: 도서 검색 시 작가 데이터가 없는 경우

- src/pages/oauth/callback/kakao.tsx
- close #193 
- 로그인 시 로그인 중이라고 render 되도록 수정하였습니다~
- 영상
> fix: 로그인 성공 시 로그인 실패했습니다 render 되는 문제

- src/layout/Layout.tsx
- src/pages/index.tsx
- src/pages/onboarding/index.tsx
- src/styles/globals.css
- tailwind.config.js
- close #198  
- 온보딩 페이지 구현
- 비로그인 유저 메인 접근 시 온보딩 페이지로 리다이렉션됩니다.
- 온보딩에서 메인으로 온 경우는 예외처리해놨습니다!
- 현재 로그인 모달 뜰 때 Link 태그로 되어있어서 '' 이 처리로 메인페이지로 이동하는 경우 온보딩페이지로 이동됩니다. 이 부분은 Link를 useRouter로 작업하여 없앨 수 있을 것 같습니다!
> feat: onboarding 페이지 구현

- src/pages/book/record/index.tsx
- close #224 
- 독서 기록 페이지 네비게이션 적용
- 독서기록버튼 disabled 조건식 수정
> feat: 네비게이션 적용, 조건식 수정

- src/api/main.ts
- src/api/record.ts
- src/components/common/ListItem/SearchResultListItem.tsx
- src/components/main/mainRecordFeed/FeedItem.tsx
- src/components/main/mainRecordFeed/RecordFeedList.tsx
- src/hooks/useInput.ts
- src/pages/book/detail/index.tsx
- src/pages/book/feed/index.tsx
- src/pages/book/record/index.tsx
- src/types/record.d.ts
- close #222 
- 피드 페이지네이션 구현
- 제가 생각한 시나리오
-----------------
메인에서 피드
도서상세에서 피드
&
마이페이지 내 책장에서 특정 책에 대한 독서기록에서 피드 
마이페이지 다른 사람 책장에서 특정 책에 대한 독서기록에서 피드 
마이페이지 내 모든 독서기록에서 피드
마이페이지 다른 모든 독서기록에서 피드
마이페이지 부분은 독서기록 작성 시 에러 때문에 작성이 안되어 테스트를 할 수 없어 보류하였습니다. 이 부분까지하고 커밋할까 생각했는데 Files changed가 많아질 것 같아 1차적으로 커밋하였습니다.
> feat: feed 구현

- src/api/recruit.ts
- src/pages/profile/index.tsx
- src/pages/profile/myfeed.tsx
- src/pages/profile/myrecruit.tsx
> feat: 나의 모임 구현

- src/api/main.ts
- src/api/recruit.ts
- src/components/main/bestRecruit/BestRecruitListItem.tsx
- src/components/recruit/detail/RecruitParticipationControl.tsx
- src/components/recruit/detail/member/MemberListItem.tsx
- src/pages/recruit/detail/index.tsx
- src/pages/recruit/detail/member.tsx
- src/recoil/modal.ts
- src/types/recruit.d.ts
- close #233 
- 멤버 페이지 api 연결하였습니다.
- 모임장일 시 멤버 페이지에서 강퇴 버튼이 보이며 강퇴가 가능합니다.
- staleTime을 짧게 변경하였는데 만약 한 유저가 데이터를 변경하도 같은 페이지를 보고 있는 다른 유저는 staleTime동안 데이터가 변경되지 않고 유지된다고 합니다! 간과하고 있던 부분이라 1분 정도로 staleTime을 일단 줄였습니다!
> feat: 그룹 멤버 관련 기능 구현

- src/components/recruit/detail/RecruitParticipationControl.tsx
- close #235  
- 모임 참여하기/탈퇴하기 버튼 클릭 후 로딩 중일 때 disabled 처리하여 중복해서 api 호출이 되지 않도록 하였습니다.
> fix: 모임 참여/탈퇴 로딩 중일 때 disabled 처리

- public/images/feed/feed-left.svg
- public/images/feed/feed-right.svg
- src/pages/book/feed/index.tsx
- close #255 
- 아이콘 추가, 글자색 변경
> design: 아이콘 추가, 글자색 변경

- src/components/common/BookShelfPreview.tsx
- tailwind.config.js
- close #245  
추천 책장 책 사이즈 통일하였습니다!
> design: 메인 추천 책장 책 사이즈 통일

- src/pages/login/index.tsx
- close #249 
- 이슈에 버그 발생 상황과 해결해야 하는 이유 작성해두었습니다~
> fix: 로그인한 유저는 로그인 페이지 접근 금지

- src/components/common/BottomNav.tsx
- close #251 
- commit 제목을 통해 작업 내역을 확인하시면 됩니다.
> design: Bottom Nav Bar 수정

- public/images/detail/down-arrow.svg
- public/images/detail/left-arrow.svg
- public/images/detail/upper-arrow.svg
- src/pages/book/detail/index.tsx
- src/pages/book/feed/index.tsx
- close #260 
- 아이콘 삽입
- 피드 페이지에서 도서 상세페이지로 데이터를 전달하지 못하는 오류 해결
> design & fix : 아이콘 삽입, 피드 -> 도서 상세 넘어가지 않는 오류 해결

- src/pages/book/record/select.tsx
- src/pages/profile/index.tsx
- src/pages/profile/myfeed.tsx
- close #270 
- 반응형 적용하여 책장, 피드 비율 수정하였습니다.
> design: 반응형적용

- src/pages/recruit/detail/index.tsx
- close #274  
독서 모임 상세 페이지 디자인 세부 사항 적용하였습니다.
- 본문 영역 그림자 적용
- 하단 padding 더 여유롭게 변경
> design: 독서 모임 상세 페이지 디자인 세부 사항 적용

- src/components/common/SearchInput.tsx
- close #278 
- 컴포넌트 재사용을 위해 이미지경로 절대경로로 수정
책 검색 페이지에서도 이미지가 잘 렌더링 됩니다.
> fix: 이미지 경로 수정

- src/api/recruit.ts
- src/components/recruit/RecruitForm.tsx
- src/pages/recruit/write.tsx
- close #273 
- 이슈에 작업 내용 작성해두었습니다.
- 결과물(화질이 좋지 않아서 모든 데이터를 입력 안 했을 경우에는 버튼이 아예 보이질 않네요 ㅠ)
> feat: 독서 모임 개설, 수정 페이지

- public/images/not-select-arrow.svg
- public/images/select-arrow.svg
- src/components/recruit/RecruitFormUserInput.tsx
- close #275 
- 이슈 및 commit 내역으로 작업 내역 확인하시면 될 것 같습니다~
- 결과물 1 => date를 입력하지 않을 경우 border color가 red)
- 결과물 2
- 온라인 버튼 클릭 시 지역 버튼 비 활성화
- 리스트 아이템 선택하면 리스트 제거
- 화살표 아이콘 애니메이션
- 지역 선택 리스트 열린 상태에서 온라인 버튼 클릭하면 리스트 닫기
- 현재 data가 입력되지 않으면 border width를 2px로 설정했는데 보시기에 많이 두껍나요?
> design: 독서 모임 개설, 수정 페이지

- src/components/recruit/RecruitInfinityScrollLists.tsx
- src/types/recruit.d.ts
- close #293 
- 이슈에 작업 이유 작성해두었습니다.
> refactor: 독서 모임 조회페이지 currentPage data type 수정

- src/pages/book/detail/index.tsx
- close #315 
-  상세 페이지 관련 기록 없을 때 컴포넌트 구현
> design: 관련 기록 없을 때 컴포넌트

- src/pages/recruit/index.tsx
> design: 독서 모임 조회 페이지 상단 일러스트 not fixed

- src/components/book/record/Calendar.module.css
- src/components/common/BottomNav.tsx
- src/components/recruit/RecruitForm.tsx
- src/pages/profile/index.tsx
- src/pages/profile/myfeed.tsx
- close #339 
- 현재 main color 색상 코드 사용하고 있는 부분 다 수정하였습니다.
- 예전 main color(#67a68a) 사용하고 있는 부분도 현재 main color로 다 수정하였습니다.
- PR 보시고 제가 건들면 안되는데 건드리 부분이 있다면 말씀해주세요.
- 각자 페이지에서 main color 필요 여부 판단해서 작업해주시면 될 것 같습니다~
> refacotr: main color 반영

- src/pages/profile/myrecruit.tsx
- close #287 
- 마이 모임 디자인, 클릭 시 상세페이지 이동
> feat & design: 마이 모임 디자인, 클릭 시 상세페이지 이동

- .gitignore
- src/components/recommend/BookRecommendGuide.tsx
- src/components/recommend/RecommendLoading.tsx
- src/components/recommend/RecommendResultModal.tsx
- src/pages/recommend/complete.tsx
- src/pages/recommend/userinput.tsx
- tailwind.config.js
- close #331  
- **`clamp` 속성을 이용**해서 글씨 반응형으로 조절하였습니다.
```tsx
clampSm: 'clamp(0.75rem, 4vw, 0.875rem)' /**14px */,
clampBase: 'clamp(0.875rem, 4vw, 1rem)' /**16px */,
clampLg: 'clamp(0.875rem, 5vw, 1.125rem)' /**18px */,
clampXl: 'clamp(1.125rem, 5vw, 1.25rem)' /**20px */,
clamp2xl: 'clamp(18px, 6vw, 1.5rem)' /**24px */,
clamp3xl: 'clamp(24px, 6vw, 30px)' /**30px */,
```
tailwind 에 위에 처럼 속성 추가해두었으니 반응형 구현하실 때 사용하시면 될 것 같아요! 기준점은 tailwind font size 기준점과 동일하게 하였습니다.
**추천페이지 반응형 적용**
- local/production api 주소 이분화로 env 파일로 분리하여 사용하면서 **gitignore에서 모든 .env 파일을 포함하도록** 파일 확장자를 수정하였습니다! 확인 부탁드립니다.
> design: 추천페이지 글씨 반응형으로 변경

- src/pages/_app.tsx
- close #367  
- 폰트 상대 경로가 제대로 되어 있음에도 불구 하고 처음에 오류가 뜨다가 다시 똑같은 경로로 작성하면 또 제대로 되더라구요! 무슨 오류인지 모르겠어서..🤔 일단 상대경로를 불필요한 부분을 없애고 다시 설정해주었습니다! 
- main 태그를 추가하면서 height 100% 설정을 안해주어서 그 부분 추가했습니다!
> fix: 폰트 상대경로 수정

- src/pages/onboarding/index.tsx
- src/styles/globals.css
- close #364 
온보딩 페이지 QA 수정 사항 반영하였습니다
- skip 버튼 클릭 범위 조절
- skip 버튼 클릭 시 마지막 슬라이드로 이동
> feat: 스킵 버튼 클릭 시 마지막 슬라이드로 이동

- src/components/common/BookShelfPreview.tsx
- src/components/main/bestRecruit/BestRecruitListItem.tsx
- src/components/main/mainRecordFeed/FeedItem.tsx
- src/components/main/mainRecordFeed/RecordFeedList.tsx
- src/pages/index.tsx
- tailwind.config.js
- close #371  
메인페이지 디자인 수정사항 적용하였습니다.
- `인기 서재 추천` -> `맞춤 서재 추천` 멘트 변경
- 전체적인 폰트 사이즈/weight 재설정
- 시멘틱 태그 설정
- 폰트 색상 재설정
> design: 메인페이지 디자인 수정사항 적용

- src/api/book.ts
- src/components/recommend/BookRecommendGuide.tsx
- src/pages/recommend/complete.tsx
- src/pages/recommend/userinput.tsx
- close #373  
- 추천페이지 책  검색 시 1권만 검색하도록 수정
- 책 검색 에러 발생 시 검색 결과 없을 때처럼 안내멘트 뜨도록 수정
- 폰트 크기, width 등 조절
추천 페이지 관련해서 로딩, 결과 페이지는 아직 디자인 수정 중이라 수정하지 못하였습니다! 디자인 나오는대로 수정하도록 하겠습니다~
> refactor: 추천페이지 수정 사항 적용

- src/components/recruit/RecruitFormUserInput.tsx
> design: 독서 모임 개설, 수정 페이지 아이콘 설정

- src/pages/profile/myfeed.tsx
- close #377 
- 마이 피드 편집 버튼 클릭시 화면이 줄어드는 현상 해결
- 마이 피드 비공개 문구 높이 차이 해결
> fix: 마이 피드 편집 버튼 클릭시 화면이 줄어드는 현상 해결

- src/pages/profile/myrecruit.tsx
> design: 외 n명 높이 수정

- src/pages/book/detail/index.tsx
- src/pages/book/feed/index.tsx
- close #381 
- 도서 상세 페이지 스크롤 위치 기억
> feat: 도서 상세 페이지 스크롤 위치 기억

- src/components/book/search/InfinityScrollLists.tsx
> design: 도서 검색 페이지 검색 결과 없을 시 comment 설정

- src/components/auth/LoginButton.tsx
- src/pages/login/index.tsx
> design: 로그인 페이지 디자인 수정

- src/pages/oauth/callback/kakao.tsx
- close #394 
- 로그인 중에 render 되는 comment를 제거하였습니다.
> design: 로그인 중이에요 comment 제거

- src/layout/ProfileLayout.tsx
- close #389 
- 로그인 한 유저가 도서 검색 => 로그아웃 후 도서 검색 페이지에 접근하면 이전에 로그인 한 유저의 검색 결과가 그대로 유지되는 문제를 해결하였습니다~
> fix: 도서 검색 결과 유지되는 문제

- src/pages/book/record/index.tsx
- close #399 
- 독서 기록 페이지 폰트 적용
> design: 독서 기록 페이지 폰트 적용

- src/pages/book/feed/index.tsx
- close #400 
- 피드 상세 페이지 폰트 적용
> design: 피드 상세 페이지 폰트 적용

- public/images/record/calendar-left.svg
- public/images/record/calendar-right.svg
- src/pages/book/record/index.tsx
- src/styles/globals.css
- close #410 
- 뒤로가기 버튼 추가
- 달력 버튼 수정
> design: 뒤로가기, 달력 버튼 수정

- src/pages/book/feed/index.tsx
- close #412 
- 배경 추가, 뒤로가기 추가
> design: 배경 추가, 뒤로가기 추가

- next.config.js
- package.json
- yarn.lock
- close #416  
번들 최적화에 사용할 수 있는 라이브러리인 bundle-analyzer 라이브러리 설치하였습니다.
```jsx
$ yarn analyze
```
명령어를 통해 실행이 가능합니다.
**사용예시 이미지**
> chore: bundle-analyzer 설치

- src/hooks/useGroupForm.ts
- close #420 
- 이슈에 작업 이유 작성해 두었습니다~
> refactor: 온라인일 경우 지역 데이터 없음을 나타내는 문자열 전달

- src/components/common/BottomNav.tsx
- src/components/common/ListItem/ReadingGroupRecruitment .tsx
- src/components/common/ListItem/SearchResultListItem.tsx
- src/components/recruit/RecruitForm.tsx
- src/components/recruit/RecruitFormUserInput.tsx
- src/pages/book/search/index.tsx
- src/pages/login/index.tsx
- src/pages/recruit/index.tsx
- close #422 
- 이슈에 진행한 작업 정리해두었습니다~
- tailwind-styled-component에서 반응형 font 사용하면 style이 적용 안되는 문제(독서 모임 개설, 수정 페이지의 온/오프라인 버튼)가 있었습니다. style이 적용되지 않는 부분은 반응형 font를 설정하지 않았습니다~
> design: font 수정 작업

- src/components/main/bestRecruit/BestRecruitList.tsx
- src/components/main/mainRecordFeed/RecordFeedList.tsx
- src/pages/index.tsx
- close #436  
책을 3권 담은 유저가 2명 이상 없을 경우 추천 책장이 빈 값이 와서 에러가 발생하고 있었습니다!
임시로 없을 때 에러 안 나도록 처리해두었습니다.
데이터 쌓이면 메인에서 인기모임이나 기록들도 디폴트로 생기게 되겠지만 일단 없을 때 처리 임의로 함께 추가해두었습니다!
> fix: 추천 책장 없을 때 처리

- src/pages/index.tsx
- close #443 
- 이전 작업에서 미로그인 시 배열이 없을 때 처리를 해주었는데 로그인 시에는 빈배열이 아니라 에러가 발생하더라구요! 그래서 관련해서 처리 추가하였습니다!
> fix: 추천 책장 에러처리 적용

- src/pages/recruit/index.tsx
- close #445 
- 수정 전 페이지
- 수정 후 페이지
> design: 독서 모임 조회 페이지 하얀색 배경 영역 확장

- src/pages/book/detail/index.tsx
- close #449 
- 책 제목 가운데 정렬 하였습니다.
> design: 책 제목 가운데 정렬

- src/pages/_app.tsx
- src/pages/_document.tsx
- close #434 
- 이전 작업이랑 비교해서 보시면 이해하기 쉬우실 겁니다!(#428) 
- dataLayer 출력 내용(기존 출력 내용에는 없던 빨간 네모 부분(측정 ID)이 출력되고 있습니다)
- 구글 애널리틱스 페이지에서 사용자가 check 되는 것을 확인할 수 있습니다!
> fix: ga 관련 코드 수정

- src/components/book/record/SelectModal.tsx
- close #453
- 도서 선택 모달 책 제목 가운데 정렬
> design: 도서 선택 모달 책 제목 가운데 정렬

- src/components/main/mainRecordFeed/FeedItem.tsx
- src/components/recruit/detail/member/MemberListItem.tsx
- src/pages/recruit/detail/index.tsx
- close #455  
사용해보면서 수정할 부분이 보여서 적용하였습니다!
- 메인 피드페이지 말줄임이 넘쳐서 width 조절하였습니다.
- 독서 상세 모임 페이지 아바타가 원이 아니어서 width, height 고정하였습니다.
> design: 메인, 독서 모임 상세페이지 디자인 수정

- package.json
- yarn.lock
- close #460 
- @next/font 삭제하였습니다
> chore: remove @next/font

- src/pages/login/index.tsx
- close #468 
- 프로덕트 환경에서 최적화 전 성능 점수 측정(`성능 점수: 93점, LCP: 1.7s`) 
- 사용하지 않는 폰트 제거(`성능 점수: 98점, LCP: 1.1s`) 
- _app.tsx hydrate error check 하는 부분 제거 및 로고 Image priority 설정(`성능 점수: 100점, LCP: 0.7s`) 
- 결론 : 최적화 작업을 통해 성능 점수를 93점에서 100점으로 올렸으며 LCP 소요시간을 59% 개선하였습니다!
- 개인적으로 hydrate error check 하는 것과 관련해서 필요한 컴포넌트에만 설정 하도록 하면 좋을 것 같습니다! 0.1s 개선이 수익률 1% 증가라는 자료 및 웹 사이트의 낮은 사용자 이탈률을 목표로 하기 위해서 해당 작업이 필요하다고 생각합니다~
> refactor: 로그인 페이지 성능 최적화

- src/layout/PrettyNightFontLayout.tsx
- src/pages/_app.tsx
- src/pages/book/feed/index.tsx
- src/pages/book/record/index.tsx
- src/pages/onboarding/index.tsx
- close #472  
고운밤 `_app` 에서 제거하고 layout 파일로 만들어서 설정하였습니다. 
혹시 설정 안 된 페이지 있으면 알려주세요!
**설정한 페이지**
- 온보딩 페이지
- 기록 페이지
- 피드 상세 페이지
> refactor: 고운밤 폰트 import 위치 변경

- src/layout/PrettyNightFontLayout.tsx
- close #480 
이전에 작업한 고운밤 폰트 적용 레이아웃 컴포넌트에서 height 100% 를 설정해주지 않아서 추가하는 작업하였습니다~
> design: 고운밤 layout 컴포넌트 height 100% 설정

- src/pages/onboarding/index.tsx
- close #433 
유의미한 점수차이는 없으나 이미지가 바로 떠야 하기 때문에  lazy loading 안되도록 priority 설정하였습니다.
> refactor: 이미지 priority 설정

- src/pages/book/detail/index.tsx
- close #487 
- 상세페이지 lighthouse seo에서 추천방법으로 속성변경하였습니다.
> feat: 상세 페이지 썸네일 속성 변경

- src/layout/ProfileLayout.tsx
- src/pages/book/feed/index.tsx
- src/pages/profile/edit.tsx
- src/pages/profile/index.tsx
- src/pages/profile/myfeed.tsx
- src/pages/profile/myrecruit.tsx
- close #504 
- 코드 스플리팅
- 이미지 최적화
- 책장: 13점 상승, lcp : 3.1s 단축
- 나의기록: 7점 상승, lcp :2.4s 단축
- 모임: 8점 상승, lcp: 4.3s 단축
- 프로필 편집 페이지: 13점 상승, lcp:4.4s 단축
> refactor: 프로필 페이지 최적화

- src/pages/book/feed/index.tsx
- close #503 
- 이미지 최적화
- 코드 스플리팅
- 성능점수 8점 상승, lcp 2.9s 단축
> refactor: 피드 페이지 최적화

- src/constants/file.ts
- close #514 
- 이미지 등록 제한 용량 5mb로 수정
> feat: 이미지 등록 제한 용량 수정

- README.md
> docs: README 배포 url 수정

- src/pages/book/record/index.tsx
- close #518 
- 독서기록 시 이미지 삽입을 하지 않을 경우 해당 도서 표지가 들어가게 하였습니다.
> feat: 독서기록 시 이미지 지정 안할 시 책 표지 자동지정

- src/components/main/recommendBookShelf/BookShelfPreview.tsx
- close #520  
추천 책장 로딩 시 로딩 멘트가 아니라 오류 멘트가 보여지고 있어서 조건 수정하였습니다!
> fix: 추천 책장 오류 멘트 조건 수정
